### ISSUE TITLE
dum.wowpin.eu allows arbitrary telnet

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [wowpin/dumserver#18]
I'm not sure where to report this, but [allowing random people to connect to random servers](http://dum.wowpin.eu/player-client/?game=sd&gh=towel.blinkenlights.nl&gp=23&cs=true&as=dbl&et=twilight&of=standard) with no authentication or sanity checks seems like a bit of an issue.

**Comment by wowpin** [comment]
It's not really an issue with dumserver codebase, but rather Dome Client, which I'm using for the existing webclient. 

I'm closing it here and raising as issue #14 in dome-client - https://github.com/JavaChilly/dome-client.js/issues/14
