### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by cherbert** [wowpin/dumserver#43]
Whenever I log in with my character I get this spammed to console. Whether using raw telnet or Mudlet

c3RhdHVzcGFuZWwChris;1;Small Bathroom;100;100;0;100;0;[None]

Also when using raw telnet (putty) I get ghost spaces every few seconds and also the layout is all messed up.

**Comment by wowpin** [comment]
Since the webclient has been incorporated into the game, other clients like Mudlet/raw telnet are no longer supported. This spam you're seeing is the server's way of passing additional information to the webclient, which then is used to populate the side panel.
